$f = 'index.html'
$c = [IO.File]::ReadAllText($f,[Text.Encoding]::UTF8)

# ── 1. BUMP OPACITY FOR BETTER VISIBILITY ──────────────────────────────
$c = [regex]::Replace($c, 'text-white/10\b', 'text-white/30')
$c = [regex]::Replace($c, 'text-white/15\b', 'text-white/40')
$c = [regex]::Replace($c, 'text-white/18\b', 'text-white/40')
$c = [regex]::Replace($c, 'text-white/20\b', 'text-white/50')
$c = [regex]::Replace($c, 'text-white/25\b', 'text-white/60')
$c = [regex]::Replace($c, 'text-white/30\b', 'text-white/70')
$c = [regex]::Replace($c, 'text-white/35\b', 'text-white/80')
$c = [regex]::Replace($c, 'text-white/40\b', 'text-white/85')
$c = [regex]::Replace($c, 'text-white/45\b', 'text-white/90')
$c = [regex]::Replace($c, 'text-white/50\b', 'text-white/95')
$c = [regex]::Replace($c, 'text-white/60\b', 'text-white')
$c = [regex]::Replace($c, 'text-white/70\b', 'text-white')
$c = [regex]::Replace($c, 'text-white/75\b', 'text-white')
$c = [regex]::Replace($c, 'text-white/82\b', 'text-white')
$c = [regex]::Replace($c, 'text-white/90\b', 'text-white')

$c = [regex]::Replace($c, 'text-accent/25\b', 'text-accent/50')
$c = [regex]::Replace($c, 'text-accent/30\b', 'text-accent/60')
$c = [regex]::Replace($c, 'text-accent/35\b', 'text-accent/70')
$c = [regex]::Replace($c, 'text-accent/40\b', 'text-accent/80')
$c = [regex]::Replace($c, 'text-accent/45\b', 'text-accent/85')
$c = [regex]::Replace($c, 'text-accent/50\b', 'text-accent/90')
$c = [regex]::Replace($c, 'text-accent/55\b', 'text-accent/90')
$c = [regex]::Replace($c, 'text-accent/60\b', 'text-accent/95')
$c = [regex]::Replace($c, 'text-accent/70\b', 'text-accent')
$c = [regex]::Replace($c, 'text-accent/80\b', 'text-accent')
$c = [regex]::Replace($c, 'text-accent/85\b', 'text-accent')

# ── 2. BUMP TEXT SIZES FOR BETTER READABILITY ──────────────────────────
$c = [regex]::Replace($c, 'text-\[0\.44rem\]', 'text-[0.55rem]')
$c = [regex]::Replace($c, 'text-\[0\.48rem\]', 'text-[0.6rem]')
$c = [regex]::Replace($c, 'text-\[0\.5rem\]', 'text-[0.65rem]')
$c = [regex]::Replace($c, 'text-\[0\.55rem\]', 'text-[0.7rem]')
$c = [regex]::Replace($c, 'text-\[0\.6rem\]', 'text-[0.75rem]')
$c = [regex]::Replace($c, 'text-\[0\.65rem\]', 'text-[0.8rem]')
$c = [regex]::Replace($c, 'text-\[0\.7rem\]', 'text-[0.85rem]')
$c = [regex]::Replace($c, 'text-\[0\.72rem\]', 'text-[0.85rem]')
$c = [regex]::Replace($c, 'text-\[0\.75rem\]', 'text-[0.85rem]')
$c = [regex]::Replace($c, 'text-\[0\.8rem\]', 'text-[0.9rem]')
$c = [regex]::Replace($c, 'text-\[0\.85rem\]', 'text-[0.95rem]')
$c = [regex]::Replace($c, 'text-\[0\.9rem\]', 'text-[1rem]')
$c = [regex]::Replace($c, 'text-\[0\.95rem\]', 'text-[1.05rem]')
$c = [regex]::Replace($c, 'text-\[1rem\]', 'text-[1.1rem]')

[IO.File]::WriteAllText($f,$c,[Text.Encoding]::UTF8)
Write-Host "Readability overhauled!"
